/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fenquen_jfsnotify_FsNotify */

#ifndef _Included_com_fenquen_jfsnotify_FsNotify
#define _Included_com_fenquen_jfsnotify_FsNotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fenquen_jfsnotify_FsNotify
 * Method:    watch0
 * Signature: (Ljava/util/concurrent/BlockingQueue;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fenquen_jfsnotify_FsNotify_watch0 (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_fenquen_jfsnotify_FsNotify
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fenquen_jfsnotify_FsNotify_stopWatch0 (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
